name: swapshelfproje
description: "A new Flutter project."
publish_to: 'none' # Projenizi pub.dev'e yayınlamayı düşünmüyorsanız bunu bırakabilirsiniz.

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^5.4.0
  cupertino_icons: ^1.0.8
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  image_picker: ^1.0.7
  firebase_storage: ^12.3.7
  permission_handler: ^10.4.5
  app_settings: ^5.1.1
  device_info_plus: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.14.1
  mockito: ^5.0.0

flutter:
  uses-material-design: true

  # Assets'lerinizin yolunu doğru tanımladığınızdan emin olun.
  assets:
    - assets/img/
